= Maintainer

== How to execute the playbook

To test the workshop/playbook against an existing OCP Cluster which has been created for this lab, run the following command
to git clone the `agnosticd` project and next start the `it.sh` script

**Remark**

Review with the RHTE team, what should be the values to be used for the following parameters:

- OCP_CONSOLE:  `https://console-openshift-console.apps.shared-dev.dev.openshift.opentlc.com`
- OCP_API:      `https://api.shared-dev.dev.openshift.opentlc.com:6443`
- TARGET_HOST:  `bastion.dev.openshift.opentlc.com`
- OCP_USERNAME: `ec2-user`

Open a terminal and execute the following commands to clone the agnosticd project and
next to apply the workshop playbook
```
git clone https://github.com/halkyonio/agnosticd.git && cd agnosticd
git checkout development
cd ..
./scripts/it.sh agnosticd/ansible/roles ACTION GUID ENV
```
where: `ACTION` corresponds to the ansible parameter to `create` or `remove`; GUID the ID of the vm created for your project and ENV` is the UAT platform to be used which is RHPDS `prod` or `dev`

Example: `./scripts/it.sh agnosticd/ansible/roles create namur-7027 prod`

*WARNING*: Before to execute the ansible playbook, it is needed first to import your public key within the VM using this command:
```
ssh-copy-id -i ~/.ssh/YOUR_SSH_PUBLIC_KEY YOUR_USER@bastion.GUID.openshiftworkshop.com
```

You can ssh to the vm's cluster using the information shared by the RHTE team if your ssh public key has been shared and imported
within the VM
```
ssh cmoulliard-redhat.com@bastion.GUID.open.redhat.com
```

== Useful links

To request the creation of a cluster: https://www.opentlc.com/gg/manager.cgi

To access the cluster created and get the GUID: www.opentlc.com/gg/gg.cgi?profile=generic_tester

To control if creation of the cluster succeeded: https://spp.opentlc.com/miq_request/show_list