= Maintainer

== How to execute the playbook

To test the workshop/playbook against an existing OCP Cluster which has been created for this lab, run the following command
to git clone the `agnosticd` project and next start the `it.sh` script

**Remark**

Review with the RHTE team, what should be the values to be used for the following parameters:

- OCP_CONSOLE:  `https://console-openshift-console.apps.shared-dev.dev.openshift.opentlc.com`
- OCP_API:      `https://api.shared-dev.dev.openshift.opentlc.com:6443`
- TARGET_HOST:  `bastion.dev.openshift.opentlc.com`
- OCP_USERNAME: `ec2-user`

Open a terminal and execute the following commands to clone the agnosticd project and
next to apply the workshop playbook
```
git clone https://github.com/halkyonio/agnosticd.git && cd agnosticd
git checkout development
cd ..
./scripts/it.sh agnosticd/ansible/roles ACTION GUID ENV
```
where: `ACTION` corresponds to the ansible parameter to `create` or `remove`; GUID the ID of the vm created for your project and ENV` is the UAT platform to be used which is RHPDS `prod` or `dev`

Example: `./scripts/it.sh agnosticd/ansible/roles create namur-7027 prod`

*WARNING*: Before to execute the ansible playbook, it is needed first to import your public key within the VM using this command:
```
ssh-copy-id -i ~/.ssh/YOUR_SSH_PUBLIC_KEY YOUR_USER@bastion.GUID.openshiftworkshop.com
```

You can ssh to the vm's cluster using the information shared by the RHTE team if your ssh public key has been shared and imported
within the VM
```
ssh cmoulliard-redhat.com@bastion.GUID.open.redhat.com
```

== Useful links

To request the creation of a cluster: https://www.opentlc.com/gg/manager.cgi

To access the cluster created and get the GUID: www.opentlc.com/gg/gg.cgi?profile=generic_tester

To control if creation of the cluster succeeded: https://spp.opentlc.com/miq_request/show_list

== How to create the cluster on Dev

GUIDGrabber tool: https://www.opentlc.com/gg/manager.cgi?operation=deploy_lab

Remember to follow the process here: https://mojo.redhat.com/docs/DOC-1165930-testing-your-red-hat-summit-lab-deployment

Log into spp.opentlc.com (using same user and password generic_tester) then go to services -> my services

so the cluster info you will get by going to : https://www.opentlc.com/gg/gg.cgi?profile=generic_tester
as documented in the mojo guide

During the event the link will be https://www.opentlc.com/gg/gg.cgi?profile=generic_rhte

Next you can do ssh lab-user@bastion.GUID.sandboxXXX.opentlc.com with password `r3dh4t1!`

```
ssh lab-user@bastion.bffb.sandbox171.opentlc.com
```

and then do sudo -i and you will be automatically logged in as cluster admin as root 🙂
Add that in your instructions
you have htpasswd users 1..200 and the admin of the cluster is opentlc-mgr
all passwords are r3dh4t1!

your bastion machine is t2.large, master is m4.xlarge and worker nodes are m4.4xlarge, all AWS instances

=== Some checks
```
oc get nodes --as=system:admin
```

=== How to log

```
USER=opentlc-mgr
PASSWORD=r3dh4t1!
oc login -u $USER -p $PASSWORD --server=https://api.cluster-bffb.bffb.sandbox171.opentlc.com:6443

USER=user1
PASSWORD=r3dh4t1!
oc login -u $USER -p $PASSWORD --server=https://api.cluster-bffb.bffb.sandbox171.opentlc.com:6443
```